### PR TITLE
Signed int keys order

### LINKED ISSUE #489: Incorrect I32Key Index Ordering
When using an I32Key as the primary key for an index, the ordering is done incorrectly. Instead of sorting signed integers as you would expect them to be sorted, all negative numbers are considered to be "greater" than all positive numbers.

IntKey new implementation: 
```
impl<T: Endian> IntKey<T> {
    pub fn new(val: T) -> Self {
        IntKey {
            wrapped: val.to_be_bytes().into(),
            data: PhantomData,
        }
    }
}
```

The new implementation converts the i32 number to big endian bytes which doesn't preserve the sorting order.

My workaround was to restrict my range query with a max of the most negative number:
```
    let zero_winnings_key = leaderboard()
        .idx
        .winnings
        .index_key((I32Key::from(0), b"".to_vec()));
    let most_negative_key = leaderboard()
        .idx
        .winnings
        .index_key((I32Key::from(-2147483648), b"".to_vec()));

    let res = leaderboard()
        .idx
        .winnings
        .range(
            deps.storage,
            Some(Bound::inclusive(zero_winnings_key)),
            Some(Bound::exclusive(most_negative_key)),
            Order::Descending,
        )
        .take(limit)
        .collect::<StdResult<Vec<_>>>()?;
```
This fits my use case because I don't need the negative values when querying, but is quite counterintuitive and took me a long time to figure out what was going on.

### PR DESCRIPTION
**Pull request by maurolacy**
Closes #489.

There are a number of different ways to do the signed int key modification (a number of different impls in the commits). Not sure what is the best one; opted for doing it without mutable slices, and without branching.

I guess the only way to know for sure would be by benchmarking them. Will create an issue for it, and we can do  in the future.

### CODE REVIEW

File: packages/storage-plus/src/int_key.rs [hunk 1]
```diff
@@ -0,0 +1,130 @@
+use std::mem;
+
+/// Our int keys are simply the big-endian representation bytes for unsigned ints,
+/// but "sign-flipped" (xored msb) big-endian bytes for signed ints.
+///
+/// So that the representation of signed integers is in the right lexicographical order.
+// TODO: Rename to `IntKey` when deprecating current `IntKey`
```
Comment (ueco-jb) [inline packages/storage-plus/src/int_key.rs:7]: Please mention that in https://github.com/CosmWasm/cw-plus/issues/570.

File: packages/storage-plus/src/keys.rs [hunk 2]
```diff
@@ -615,7 +626,7 @@ mod test {
         assert_eq!(pair.prefix(), vec![one.as_slice(), two.as_slice()]);
 
         let pair: (i8, &[u8]) = (123, b"random");
-        let one: Vec<u8> = vec![123];
+        let one: Vec<u8> = vec![123 + 128];
```
Comment (ueco-jb) [inline packages/storage-plus/src/keys.rs:629]: This might look reasonable now, but for some time (and for other dev) this "magic" addition might... not add up (see what I did there?).
Either assign some const to `128` or add some comments maybe.

**Review by ueco-jb — COMMENTED** [review]
Good to see that this idea actually worked just fine.

File: packages/storage-plus/src/keys.rs (hunk 2 above)
Comment (maurolacy) [reply packages/storage-plus/src/keys.rs:629]: You are right. Perhaps doing `vec![123 ^ 0x80];` is clearer?

File: packages/storage-plus/src/keys.rs [hunk 3]
```diff
@@ -326,16 +327,26 @@ impl<'a, T: Endian> Prefixer<'a> for IntKey<T> {
...
+#[deprecated(note = "It is suggested to use `u16` as key type instead of the `U16Key` wrapper")]
 pub type U16Key = IntKey<u16>;
+#[deprecated(note = "It is suggested to use `u32` as key type instead of the `U32Key` wrapper")]
 pub type U32Key = IntKey<u32>;
+#[deprecated(note = "It is suggested to use `u64` as key type instead of the `U64Key` wrapper")]
 pub type U64Key = IntKey<u64>;
+#[deprecated(note = "Consider using 64-bit keys instead of the `U128Key` wrapper")]
 pub type U128Key = IntKey<u128>;
 
+#[deprecated(note = "It is suggested to use `i8` as key type instead of the `I8Key` wrapper")]
```
Comment (ethanfrey) [inline packages/storage-plus/src/keys.rs:341]: nice

File: packages/storage-plus/src/int_key.rs [hunk 4]
```diff
@@ -0,0 +1,130 @@
...
+mod test {
+    use super::*;
+
+    #[test]
+    fn x8_int_key_works() {
+        let k: u8 = 42u8;
+        assert_eq!(k.to_cw_bytes(), k.to_be_bytes());
+
+        let k: i8 = 42i8;
+        assert_eq!(k.to_cw_bytes(), (k as u8 ^ 0x80).to_be_bytes());
```
Comment (ethanfrey) [inline packages/storage-plus/src/int_key.rs:65]: again, I'd like the expected results to be explicit

**Review by ethanfrey — COMMENTED** [review]
looks good.
I would clean up the test cases to be more explicit rather than just contain the same math being tested

File: packages/storage-plus/src/int_key.rs (hunk 4 above)
Comment (maurolacy) [reply packages/storage-plus/src/int_key.rs:65]: Will do.

**Review by ueco-jb — APPROVED** [review]
lgtm
Personally I'd replace couple big numbers with constants for better transparency, but overall it's fine.
